package: asset_import
version: '1.3.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/asset_import


requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.2'

page:
    perm: asset_import[]
    title: 'translate:asset_import_title'
    icon: rex-icon fa-cloud-download
    subpages:
        main: 
            title: 'translate:asset_import_media'
        direct:
            title: 'translate:asset_import_direct_title'
        config:
            title: 'translate:asset_import_settings'
            perm: admin[]
